/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodersRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.CodersRecord> implements org.jooq.Record9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Long> {

	private static final long serialVersionUID = -110562415;

	/**
	 * Setter for <code>public.coders.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.coders.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.coders.age</code>.
	 */
	public void setAge(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.coders.age</code>.
	 */
	public java.lang.Long getAge() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.coders.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.coders.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.coders.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.coders.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.coders.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.coders.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.coders.image</code>.
	 */
	public void setImage(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.coders.image</code>.
	 */
	public java.lang.String getImage() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.coders.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.coders.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.coders.is_verified</code>.
	 */
	public void setIsVerified(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.coders.is_verified</code>.
	 */
	public java.lang.Boolean getIsVerified() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.coders.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.coders.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Long> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Long> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Coders.CODERS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return tech.codingclub.helix.tables.Coders.CODERS.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Coders.CODERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.helix.tables.Coders.CODERS.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.helix.tables.Coders.CODERS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.helix.tables.Coders.CODERS.IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.helix.tables.Coders.CODERS.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return tech.codingclub.helix.tables.Coders.CODERS.IS_VERIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return tech.codingclub.helix.tables.Coders.CODERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIsVerified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value2(java.lang.Long value) {
		setAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value4(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value5(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value6(java.lang.String value) {
		setImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value7(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value8(java.lang.Boolean value) {
		setIsVerified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord value9(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CodersRecord values(java.lang.String value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.Boolean value8, java.lang.Long value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CodersRecord
	 */
	public CodersRecord() {
		super(tech.codingclub.helix.tables.Coders.CODERS);
	}

	/**
	 * Create a detached, initialised CodersRecord
	 */
	public CodersRecord(java.lang.String name, java.lang.Long age, java.lang.String email, java.lang.String role, java.lang.String password, java.lang.String image, java.lang.String token, java.lang.Boolean isVerified, java.lang.Long id) {
		super(tech.codingclub.helix.tables.Coders.CODERS);

		setValue(0, name);
		setValue(1, age);
		setValue(2, email);
		setValue(3, role);
		setValue(4, password);
		setValue(5, image);
		setValue(6, token);
		setValue(7, isVerified);
		setValue(8, id);
	}
}
