/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coders extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.CodersRecord> {

	private static final long serialVersionUID = -1521350258;

	/**
	 * The singleton instance of <code>public.coders</code>
	 */
	public static final tech.codingclub.helix.tables.Coders CODERS = new tech.codingclub.helix.tables.Coders();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.CodersRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.CodersRecord.class;
	}

	/**
	 * The column <code>public.coders.name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.coders.age</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.Long> AGE = createField("age", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.coders.email</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.coders.role</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.coders.password</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.coders.image</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> IMAGE = createField("image", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.coders.token</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.coders.is_verified</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.Boolean> IS_VERIFIED = createField("is_verified", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.coders.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CodersRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.coders</code> table reference
	 */
	public Coders() {
		this("coders", null);
	}

	/**
	 * Create an aliased <code>public.coders</code> table reference
	 */
	public Coders(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Coders.CODERS);
	}

	private Coders(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CodersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Coders(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CodersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.CodersRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_CODERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CodersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CodersRecord>>asList(tech.codingclub.helix.Keys.EMAIL_USERNAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Coders as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Coders(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Coders rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Coders(name, null);
	}
}
